### PR TITLE
Conditional contextual bandit

### LINKED ISSUE #93: Add test for CCB no model exploration
It seems to be doing the incorrect thing in C# currently. Two 0 actions were witnessed

### PR DESCRIPTION
**Pull request by jackgerrits**
Fixes #93

### CODE REVIEW

File: rlclientlib/vw_model/vw_model.h [hunk 1]
```diff
@@ -11,8 +11,10 @@ namespace reinforcement_learning { namespace model_management {
   class vw_model : public i_model {
   public:
     vw_model(i_trace* trace_logger);
+    vw_model(i_trace* trace_logger, std::string& initial_command_line);
     int update(const model_data& data, bool& model_ready, api_status* status = nullptr) override;
     int choose_rank(uint64_t rnd_seed, const char* features, std::vector<int>& action_ids, std::vector<float>& action_pdf, std::string& model_version, api_status* status = nullptr) override;
+    int request_decision(std::vector<const char*>& event_ids, const char* features, std::vector<std::vector<size_t>>& actions_ids, std::vector<std::vector<float>>& action_pdfs, std::string& model_version, api_status* status = nullptr) override;
```
Comment (ataymano) [inline rlclientlib/vw_model/vw_model.h]: const vector<const char*>& event_ids?

File: rlclientlib/vw_model/vw_model.cc [hunk 2]
```diff
@@ -11,10 +11,14 @@ namespace reinforcement_learning { namespace model_management {
     _vw_pool(nullptr), _trace_logger(trace_logger) {
   }
 
+  vw_model::vw_model(i_trace* trace_logger, std::string& initial_command_line) :
```
Comment (ataymano) [inline rlclientlib/vw_model/vw_model.cc]: const string&?

File: rlclientlib/sampling.cc [hunk 3]
```diff
@@ -1,12 +1,50 @@
...
+    response.push_back(action_ids[idx], pdf[idx]);
+  }
+
+  RETURN_IF_FAIL(response.set_chosen_action_id(action_ids[chosen_action_index]));
+  response.set_model_id(std::move(model_id));
+  return error_code::success;
+}
+
+// TODO: write test for this
+int populate_response(std::vector<std::vector<size_t>>& action_ids, std::vector<std::vector<float>>& pdfs, std::vector<const char*>& event_ids, std::string&& model_id, decision_response& response, i_trace* trace_logger, api_status* status) {
```
Comment (ataymano) [inline rlclientlib/sampling.cc]: const action_ids, const pdfs

File: rlclientlib/ranking_event.h [hunk 4]
```diff
@@ -46,13 +50,15 @@ namespace reinforcement_learning {
     const std::vector<float>& get_probabilities() const;
     const std::string& get_model_id() const;
     bool get_defered_action() const;
-  
+    const std::string& get_event_id() const {return get_seed_id();}
```
Comment (ataymano) [inline rlclientlib/ranking_event.h]: It is weird that get_event_id is re-using get_seed_id - they accidentally share implementation right now, but there is no real dependency between them.

File: rlclientlib/ranking_event.cc [hunk 5]
```diff
@@ -48,6 +46,40 @@ namespace reinforcement_learning {
     return ranking_event(event_id, flags & action_flags::DEFERRED, pass_prob, context, resp, ts);
   }
 
+  decision_ranking_event::decision_ranking_event() { }
+
+  decision_ranking_event::decision_ranking_event(std::vector<const char*> event_ids, bool deferred_action, float pass_prob, const char* context, const decision_response& response, const timestamp& ts)
```
Comment (ataymano) [inline rlclientlib/ranking_event.cc]: const vector&?

File: rlclientlib/ranking_event.cc [hunk 6]
```diff
@@ -48,6 +46,40 @@ namespace reinforcement_learning {
...
+  }
+
+  const std::vector<unsigned char>& decision_ranking_event::get_context() const { return _context; }
+  const std::vector<std::vector<uint32_t>>& decision_ranking_event::get_actions_ids() const { return _action_ids_vector; }
+  const std::vector<std::vector<float>>& decision_ranking_event::get_probabilities() const { return _probilities_vector; }
+  const std::string& decision_ranking_event::get_model_id() const { return _model_id; }
+  bool decision_ranking_event::get_defered_action() const { return _deferred_action; }
+  const std::vector<std::string>& decision_ranking_event::get_event_ids() const { return _event_ids; }
+
+  decision_ranking_event decision_ranking_event::request_decision(std::vector<const char*> event_ids, const char* context, unsigned int flags,
```
Comment (ataymano) [inline rlclientlib/ranking_event.cc]: const vector&?

File: rlclientlib/utility/context_helper.cc [hunk 7]
```diff
@@ -41,4 +44,64 @@ namespace reinforcement_learning { namespace utility {
       RETURN_ERROR_LS(trace, status, json_parse_error) << error_code::unknown_s;
     }
   }
+
+  int get_event_ids(std::map<size_t, std::string>& event_ids, const char *context, i_trace* trace, api_status* status) {
```
Comment (ataymano) [inline rlclientlib/utility/context_helper.cc]: Can we move output (and non-const) variables after input (and const) ones? It improves readability.

File: rlclientlib/live_model_impl.cc [hunk 8]
```diff
@@ -83,6 +85,59 @@ namespace reinforcement_learning {
...
+  {
+    resp.clear();
+    //clear previous errors if any
+    api_status::try_clear(status);
+
+    //check arguments
+    RETURN_IF_FAIL(check_null_or_empty(context_json, status));
+
+    // Ensure multi comes before slots, this is a current limitation of the parser.
+    RETURN_IF_FAIL(utility::validate_multi_before_slots(context_json, nullptr, status));
```
Comment (ataymano) [inline rlclientlib/live_model_impl.cc]: Why we do not want to provide trace_logger here (and few below calls - get_slot_count, get_event_ids)?

File: rlclientlib/ranking_event.h (hunk 4 above)
Comment (jackgerrits) [reply rlclientlib/ranking_event.h]: Spoke offline - the overload of this value is something to keep in mind as we continue to work on these objects

File: rlclientlib/live_model_impl.cc (hunk 8 above)
Comment (jackgerrits) [reply rlclientlib/live_model_impl.cc]: Good catch, thanks!

File: include/decision_response.h [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+#include <vector>
+
+#include "ranking_response.h"
+
+namespace reinforcement_learning {
+  class api_status;
+
+  class decision_response {
+  public:
+    using coll_t = std::vector<ranking_response>;
```
Comment (rajan-chari) [inline include/decision_response.h]: In ranking_response, we moved away from stl collections in the public interface due to concerns that collections that might be compiled with different flags.  This resulted in defining iterators independely of stl.

File: include/decision_response.h [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+    using iterator_t = coll_t::iterator;
```
Comment (rajan-chari) [inline include/decision_response.h]: ranking_response was a compromise for CB where we had to expose multiple actions although the underlying algorithm only dealt properly with one action.
With CCB now we can deal with multiple actions.  Given that, isn't a more natural interface collection of <actionid,eventid>?

File: include/live_model.h [hunk 11]
```diff
@@ -136,7 +137,34 @@ namespace reinforcement_learning {
...
+    * per slot by sampling the probability distribution produced per slot. A unique event_id can be
+    * supplied for each slot using the `_id` json field. The corresponding event_id should be used
+    * when reporting the outcome for each slot.
+    * @param context_json Contains slots, slot_features, slot ids, actions, action features and context features in json format
+    * @param flags Action flags (see action_flags.h)
+    * @param resp Decision response contains the chosen action per slot, probability distribution used for sampling actions and ranked actions.
+    * @param status  Optional field with detailed string description if there is an error
+    * @return int Return error code.  This will also be returned in the api_status object
+    */
+    int request_decision(const char * context_json, unsigned int flags, decision_response& resp, api_status* status = nullptr);
```
Comment (rajan-chari) [inline include/live_model.h]: Given that we want to move to a FB based interface, should we indicate somehow that this interface is deprecated?  A more natural example_builder would be the right interface going forward.

File: include/live_model.h [hunk 12]
```diff
@@ -136,7 +137,34 @@ namespace reinforcement_learning {
...
+    * action features, slot feautres and context features. The inference library chooses an action
+    * per slot by sampling the probability distribution produced per slot. A unique event_id can be
+    * supplied for each slot using the `_id` json field. The corresponding event_id should be used
+    * when reporting the outcome for each slot.
+    * @param context_json Contains slots, slot_features, slot ids, actions, action features and context features in json format
+    * @param resp Decision response contains the chosen action per slot, probability distribution used for sampling actions and ranked actions.
+    * @param status  Optional field with detailed string description if there is an error
+    * @return int Return error code.  This will also be returned in the api_status object
+    */
+    int request_decision(const char * context_json, decision_response& resp, api_status* status = nullptr);
```
Comment (rajan-chari) [inline include/live_model.h]: Deprecated?

File: include/live_model.h [hunk 13]
```diff
@@ -153,7 +153,7 @@ namespace reinforcement_learning {
     int request_decision(const char * context_json, unsigned int flags, decision_response& resp, api_status* status = nullptr);
```
Comment (jackgerrits) [inline include/live_model.h]: Can you also add the deprecated attribute similar to what we do in VW? https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/vw.h#L42

**Comment by jackgerrits** [comment]
LGTM - thanks @ataymano, the container iterator looks good

File: bindings/cs/rl.net/DecisionResponse.cs [hunk 14]
```diff
@@ -0,0 +1,190 @@
...
+namespace Rl.Net {
+    namespace Native
+    {
+        internal partial class NativeMethods
+        {
+            [DllImport("rl.net.native.dll")]
+            public static extern IntPtr CreateSlotResponse();
+
+            [DllImport("rl.net.native.dll")]
+            public static extern void DeleteSlotResponse(IntPtr slotResponse);
```
Comment (lokitoth) [inline bindings/cs/rl.net/DecisionResponse.cs]: This is not used, since the NativeObject never owns the handle; we should consider removing it.

File: rlclientlib/factory_resolver.cc [hunk 15]
```diff
@@ -68,6 +68,13 @@ namespace reinforcement_learning {
     return error_code::success;
   }
 
+  template <>
+  int model_create<m::vw_model>(m::i_model** retval, const u::configuration& c, i_trace* trace_logger, api_status* status)
```
Comment (lokitoth) [inline rlclientlib/factory_resolver.cc]: Why do we need this explicit special-case? It looks identical to the generic template above it.
